### ISSUE TITLE
Enable Codecov

### ISSUE THREAD

**Issue by AlexBuccheri** [nomad-coe/matid#4]
Hi Lauri, in case no one enabled codecov yet, I just did it for this project. 
To use it in actions:

```yaml
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

I set the secret name as recommended, above.

Cheers,
Alex
